# Generated by Django 3.1.3 on 2020-11-30 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email ...@....com', max_length=254, verbose_name='Email')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('create_date', models.DateTimeField(verbose_name='Create')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Change')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.status')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('create_date', models.DateTimeField(verbose_name='Create')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Change')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('web_site', models.URLField(max_length=100, verbose_name='Web site')),
                ('option', models.CharField(max_length=30, verbose_name='Option')),
                ('since', models.CharField(max_length=4, verbose_name='Since')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('create_date', models.DateTimeField(verbose_name='Create')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Change')),
                ('cities', models.ManyToManyField(to='main.City')),
                ('country', models.ManyToManyField(to='main.Country')),
                ('email', models.ManyToManyField(to='performer.Email')),
            ],
            options={
                'verbose_name': 'Performer',
                'verbose_name_plural': 'Performers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='///', max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('create_date', models.DateTimeField(verbose_name='Create')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Change')),
                ('groups', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performer.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('reviews', models.TextField(max_length=300, verbose_name='Reviews')),
                ('create_date', models.DateTimeField(verbose_name='Create')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Change')),
                ('performers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performer.performer')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='+...........', max_length=10, verbose_name='Number')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('create_date', models.DateTimeField(verbose_name='Create')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Change')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.status')),
            ],
        ),
        migrations.AddField(
            model_name='performer',
            name='phones',
            field=models.ManyToManyField(to='performer.Phone'),
        ),
        migrations.AddField(
            model_name='performer',
            name='provinces',
            field=models.ManyToManyField(to='main.Provinces'),
        ),
        migrations.AddField(
            model_name='performer',
            name='specializations',
            field=models.ManyToManyField(to='performer.Specialization'),
        ),
        migrations.AddField(
            model_name='performer',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.status'),
        ),
    ]
