# Generated by Django 3.1.3 on 2020-11-30 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('create_date', models.DateTimeField(verbose_name='Create')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Change')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='///', max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('create_date', models.DateTimeField(verbose_name='Create')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Change')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('create_date', models.DateTimeField(verbose_name='Create')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Change')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('create_date', models.DateTimeField(verbose_name='Create')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Change')),
                ('provinces', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.provinces')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Сities',
                'ordering': ['name'],
            },
        ),
    ]
